public class aparnaAddress {
  
    public void getAddress(){
         latestAddress la = new latestAddress();
        
         la.firstName = 'Aparna';
         la.lastName =  'Akkina';
         la.postCode = 500060;
             
         //la.city = 'Hyderabad';
         //la.state = 'Telangana';
         //la.country = 'India';
         latestAddress.city = 'Hyderabad';
         
        // system.debug('First Name :'+la.firstName + 'Last Name :'+la.lastName +'City : '+la.city);
         
    }
    
  
}