public class AsyncFuture {
    @future
    public static void methodOne(){
        system.debug('Part 1');
    }
    
    @future
    public static void methodTwo(){
        system.debug('Part 2');
    }
    @future
    public static void methodThree(){
        system.debug('Part 3');
    }
    @future
    public static void methodOnea(){
        system.debug('Part 1');
    }
    
    @future
    public static void methodTwob(){
        system.debug('Part 2');
    }
    @future
    public static void methodThreec(){
        system.debug('Part 3');
    }
    @future
    public static void methodOned(){
        system.debug('Part 1');
    }
    
    @future
    public static void methodTwoe(){
        system.debug('Part 2');
    }
    @future
    public static void methodThreef(){
        system.debug('Part 3');
    }
    @future
    public static void methodOneg(){
        system.debug('Part 1');
    }
    
    @future
    public static void methodTwoh(){
        system.debug('Part 2');
    }
    @future
    public static void methodThreei(){
        system.debug('Part 3');
    }
    @future
    public static void methodOnej(){
        system.debug('Part 1');
    }
    
    @future
    public static void methodTwok(){
        system.debug('Part 2');
    }
    @future
    public static void methodThreel(){
        system.debug('Part 3');
    }
    @future
    public static void methodOnem(){
        system.debug('Part 1');
    }
    
    @future
    public static void methodTwon(){
        system.debug('Part 2');
    }
    @future
    public static void methodThree0(){
        system.debug('Part 3');
    }
    @future
    public static void methodOnep(){
        system.debug('Part 1');
    }
    
    @future
    public static void methodTwoq(){
        system.debug('Part 2');
    }
    @future
    public static void methodThreer(){
        system.debug('Part 3');
    }
    @future
    public static void methodOnes(){
        system.debug('Part 1');
    }
    
    @future
    public static void methodTwot(){
        system.debug('Part 2');
    }
    @future
    public static void methodThreeu(){
        system.debug('Part 3');
    }
    @future
    public static void methodOnev(){
        system.debug('Part 1');
    }
    
    @future
    public static void methodTwow(){
        system.debug('Part 2');
    }
    @future
    public static void methodThreex(){
        system.debug('Part 3');
    }
    @future
    public static void methodOney(){
        system.debug('Part 1');
    }
    
    @future
    public static void methodTwoaa(){
        system.debug('Part 2');
    }
    @future
    public static void methodThreebb(){
        system.debug('Part 3');
    }
    @future
    public static void methodOnecc(){
        system.debug('Part 1');
    }
    
    @future
    public static void methodTwodd(){
        system.debug('Part 2');
    }
    @future
    public static void methodThreeee(){
        system.debug('Part 3');
    }
    @future
    public static void methodOneff(){
        system.debug('Part 1');
    }
    
    @future
    public static void methodTwogg(){
        system.debug('Part 2');
    }
    @future
    public static void methodThreehh(){
        system.debug('Part 3');
    }
    @future
    public static void methodOneii(){
        system.debug('Part 1');
    }
    
    @future
    public static void methodTwojj(){
        system.debug('Part 2');
    }
    @future
    public static void methodThreekk(){
        system.debug('Part 3');
    }
    @future
    public static void methodOnell(){
        system.debug('Part 1');
    }
    
    @future
    public static void methodTwomm(){
        system.debug('Part 2');
    }
    @future
    public static void methodThreenn(){
        system.debug('Part 3');
    }
    @future
    public static void methodOneoo(){
        system.debug('Part 1');
    }
    
    @future
    public static void methodTwopp(){
        system.debug('Part 2');
    }
    @future
    public static void methodThreeqq(){
        system.debug('Part 3');
    }
    @future
    public static void methodOnerr(){
        system.debug('Part 1');
    }
    
    @future
    public static void methodTwoss(){
        system.debug('Part 2');
    }
    @future
    public static void methodThreett(){
        system.debug('Part 3');
    }
    @future
    public static void methodOneuu(){
        system.debug('Part 1');
    }
    
    @future
    public static void methodTwovv(){
        system.debug('Part 2');
    }
    @future
    public static void methodThreeww(){
        system.debug('Part 3');
    }
    @future
    public static void methodOnexx(){
        system.debug('Part 1');
    }
    
    @future
    public static void methodTwoyy(){
        system.debug('Part 2');
    }
    @future
    public static void methodThreeaaa(){
        system.debug('Part 3');
    }
}